#ifndef H_BOUNDARY
	#define H_BOUNDARY
	

#undef  BACK_WALL_VELOCITY_NOSLIP
#define BACK_WALL_VELOCITY_FREESLIP
#undef  FRONT_WALL_VELOCITY_NOSLIP
#define FRONT_WALL_VELOCITY_FREESLIP


#define   BOTTOM_WALL_VELOCITY_NOSLIP
#undef  BOTTOM_WALL_VELOCITY_FREESLIP
#undef   TOP_WALL_VELOCITY_NOSLIP
#define  TOP_WALL_VELOCITY_FREESLIP


#define LEFT_WALL_VELOCITY_NOSLIP
#undef  LEFT_WALL_VELOCITY_FREESLIP
#define RIGHT_WALL_VELOCITY_NOSLIP
#undef RIGHT_WALL_VELOCITY_FREESLIP

/* Just for test cases */
#undef DRIVEN_CAVITY


#endif
